/**
 * @file solvers.hpp
 * @brief Complex Numerical Engine for Algebraic Systems.
 * 
 * Objective:
 * This file encapsulates the heavy mathematical logic required to resolve
 * the linear and non-linear systems generated by physical models.
 * 
 * Architectural Rationale:
 * Segregating solvers isolates the "Brute Force" of numerical analysis ($Ax=b$, 
 * $f(x)=0$) from the "Elegance" of physical governing equations. 
 * This ensures that improvements in matrix inversion or convergence 
 * algorithms (e.g., swapping LU for iterative CG) do not require physical 
 * module refactoring.
 * 
 * Strategic Importance:
 * It enables "Plug-and-Play" numerics. A developer can independently 
 * optimize how a system is solved without knowing the specific physics 
 * (Pressure vs Temperature) that generated the system.
 */
#pragma once
#include "modules.hpp"
#include <vector>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <functional>

#include "iterative_solvers.hpp"

namespace num {
using namespace top;

/**
 * @brief Dense LU Linear Solver with Partial Pivoting.
 * 
 * Fits With: 
 * - Deterministic solution for any square, non-singular linear system.
 * - Small to medium sized dense matrices.
 */
class LUSolver : public ISolver {
public:
    Vector solve(const IModel& model, const IState& state, double dt) override {
        auto state_old = state.clone();
        Vector R = model.build_residual(state, *state_old, dt);
        Matrix J = model.build_jacobian(state, dt);
        // Standard Newton-Raphson update: J * delta = -R
        return solve_system(J, scale(R, -1.0));
    }

    Vector solve_system(Matrix A, Vector b) {
        int n = b.size();
        for (int i = 0; i < n; i++) {
            int pivot = i;
            for (int j = i + 1; j < n; j++) {
                if (std::abs(A[j][i]) > std::abs(A[pivot][i])) pivot = j;
            }
            std::swap(A[i], A[pivot]);
            std::swap(b[i], b[pivot]);
            
            if (std::abs(A[i][i]) < 1e-18) continue; 
            
            for (int j = i + 1; j < n; j++) {
                double factor = A[j][i] / A[i][i];
                b[j] -= factor * b[i];
                for (int k = i; k < n; k++) {
                    A[j][k] -= factor * A[i][k];
                }
            }
        }
        Vector x(n, 0.0);
        for (int i = n - 1; i >= 0; i--) {
            if (std::abs(A[i][i]) < 1e-18) continue;
            double sum = 0;
            for (int j = i + 1; j < n; j++) sum += A[i][j] * x[j];
            x[i] = (b[i] - sum) / A[i][i];
        }
        return x;
    }

private:
    Vector scale(const Vector& v, double s) {
        Vector res = v;
        for (auto& val : res) val *= s;
        return res;
    }
};

/**
 * @brief Specialized Tridiagonal Solver (Thomas Algorithm).
 * 
 * Fits With:
 * - 1D discretized partial differential equations (e.g., Heat 1D, Reservoir 1D).
 */
class LinearTridiagonalSolver : public ISolver {
public:
    Vector solve(const IModel& model, const IState& state, double dt) override { 
        auto state_old = state.clone();
        Vector R = model.build_residual(state, *state_old, dt);
        Matrix J = model.build_jacobian(state, dt);
        return solve_system(J, scale(R, -1.0));
    }

    /**
     * @brief Resolves a tridiagonal system using the Thomas Algorithm.
     */
    Vector solve_system(const Matrix& A, const Vector& b) {
        int n = b.size();
        if (n == 0) return {};
        if (n == 1) return {b[0] / A[0][0]};

        Vector c_star(n, 0.0);
        Vector d_star(n, 0.0);
        Vector x(n, 0.0);

        // Forward elimination
        c_star[0] = A[0][1] / A[0][0];
        d_star[0] = b[0] / A[0][0];

        for (int i = 1; i < n; i++) {
            double den = (A[i][i] - A[i][i-1] * c_star[i-1]);
            double m = 1.0 / den;
            if (i < n - 1) {
                c_star[i] = A[i][i+1] * m;
            }
            d_star[i] = (b[i] - A[i][i-1] * d_star[i-1]) * m;
        }

        // Backward substitution
        x[n-1] = d_star[n-1];
        for (int i = n - 2; i >= 0; i--) {
            x[i] = d_star[i] - c_star[i] * x[i+1];
        }

        return x;
    }

private:
    Vector scale(const Vector& v, double s) {
        Vector res = v;
        for (auto& val : res) val *= s;
        return res;
    }
};

/**
 * @brief Conjugate Gradient Iterative Solver.
 * 
 * Fits With:
 * - Large, sparse, Symmetric Positive Definite (SPD) matrices.
 */
class ConjugateGradientSolver : public ISolver {
public:
    Vector solve(const IModel& model, const IState& state, double dt) override {
        auto state_old = state.clone();
        Vector R = model.build_residual(state, *state_old, dt);
        
        // Setup matrix-vector operator for J * v
        auto apply_A = [&](const Vector& v) {
            return model.apply_jacobian(state, v, dt);
        };

        Vector guess(R.size(), 0.0);
        // Solve J * delta = -R
        return solve_iterative(apply_A, scale(R, -1.0), guess);
    }
    
    Vector solve_iterative(std::function<Vector(const Vector&)> A_func, Vector b, Vector x0, 
                           double tol = 1e-6, int max_iter = 1000) {
        int n = b.size();
        Vector x = x0;
        Vector r = subtract(b, A_func(x));
        Vector p = r;
        double rsold = dot(r, r);

        for (int i = 0; i < max_iter; i++) {
            Vector Ap = A_func(p);
            double alpha = rsold / dot(p, Ap);
            x = add(x, scale(p, alpha));
            r = subtract(r, scale(Ap, alpha));
            double rsnew = dot(r, r);
            if (std::sqrt(rsnew) < tol) break;
            p = add(r, scale(p, rsnew / rsold));
            rsold = rsnew;
        }
        return x;
    }

private:
    double dot(const Vector& a, const Vector& b) {
        double res = 0;
        for (size_t i = 0; i < a.size(); i++) res += a[i] * b[i];
        return res;
    }
    Vector add(Vector a, Vector b) {
        for (size_t i = 0; i < a.size(); i++) a[i] += b[i];
        return a;
    }
    Vector subtract(Vector a, Vector b) {
        for (size_t i = 0; i < a.size(); i++) a[i] -= b[i];
        return a;
    }
    Vector scale(Vector a, double s) {
        for (size_t i = 0; i < a.size(); i++) a[i] *= s;
        return a;
    }
};

/**
 * @brief Robust Newton-Raphson Solver with Backtracking Line Search.
 * 
 * Fits With:
 * - Non-linear systems of equations (e.g., Multiphase Reservoir flow, Implicit Heat with non-linear conductivity).
 * 
 * Best Case:
 * - Initial guess is within the "radius of convergence" of the solution.
 * - Smooth, differentiable functions with well-behaved Jacobians.
 * 
 * Worst Case:
 * - Discontinuous functions or singular Jacobians (divergence).
 * - Highly oscillating residuals where line search fails to find a descent direction.
 * 
 * Sample Input:
 * @param model An IModel implementation that provides build_residual() and build_jacobian().
 * @param state The current IState (updated in-place if converged).
 * @param dt Time step for implicit formulation.
 * @param tolerance Convergence criteria for the residual norm (e.g., 1e-4).
 */
class NewtonSolver : public ISolver {
public:
    struct ConvergenceInfo {
        bool converged;
        int iterations;
        double final_norm;
        Vector cumulative_delta; 
    };

    Vector solve(const IModel& model, const IState& state, double dt) override {
        auto state_work = state.clone();
        auto info = solve_robust(model, *state_work, dt);
        return info.cumulative_delta; 
    }

    static ConvergenceInfo solve_robust(const IModel& model, IState& state, double dt, 
                                        double tolerance = 1e-4, int max_iter = 12) {
        auto state_old = state.clone();
        Vector total_delta;

        for (int iter = 0; iter < max_iter; ++iter) {
            Vector R = model.build_residual(state, *state_old, dt);
            double norm = 0; 
            #pragma omp parallel for reduction(+:norm)
            for (int i = 0; i < (int)R.size(); ++i) norm += R[i] * R[i];
            norm = std::sqrt(norm);
            
            if (iter == 0) total_delta = Vector(R.size(), 0.0);
            if (norm < tolerance) return {true, iter, norm, total_delta};

            Vector delta;
            SparseMatrix S = model.build_sparse_jacobian(state, dt);
            
            if (S.rows > 0) {
                // High-performance Sparse Solve
                delta = BiCGSTABSolver::solve(S, scale_parallel(R, -1.0), 1e-8, 1000, true);
            } else {
                // Legacy Dense Solve (Slow)
                Matrix J = model.build_jacobian(state, dt);
                LUSolver lu;
                delta = lu.solve_system(J, scale(R, -1.0));
            }
            
            double omega = 1.0;
            double norm_initial = norm;
            bool descent_found = false;

            for (int ls = 0; ls < 6; ++ls) {
                auto state_trial = state.clone();
                state_trial->update(scale_parallel(delta, omega));
                
                Vector R_trial = model.build_residual(*state_trial, *state_old, dt);
                double norm_trial = 0;
                #pragma omp parallel for reduction(+:norm_trial)
                for (int i = 0; i < (int)R_trial.size(); ++i) norm_trial += R_trial[i] * R_trial[i];
                norm_trial = std::sqrt(norm_trial);
                
                if (norm_trial < norm_initial * 0.999) { 
                    Vector step = scale_parallel(delta, omega);
                    state.update(step);
                    #pragma omp parallel for
                    for (int i = 0; i < (int)total_delta.size(); i++) total_delta[i] += step[i];
                    norm = norm_trial;
                    descent_found = true;
                    break;
                }
                omega *= 0.25;
            }

            if (!descent_found) {
                Vector step = scale_parallel(delta, 0.001);
                state.update(step);
                #pragma omp parallel for
                for (int i = 0; i < (int)total_delta.size(); i++) total_delta[i] += step[i];
            }
            
            std::cout << "  Iter " << iter << ": Norm = " << norm << " (Omega = " << omega << ")" << std::endl;
        }
        return {false, max_iter, 0.0, total_delta};
    }

private:
    static Vector scale_parallel(const Vector& v, double s) {
        Vector res = v;
        #pragma omp parallel for
        for (int i = 0; i < (int)res.size(); ++i) res[i] *= s;
        return res;
    }

    static Vector scale(const Vector& v, double s) {
        Vector res = v;
        for (double& x : res) x *= s;
        return res;
    }
};

} // namespace num
